### ISSUE TITLE
CPv3 - Adding Access Control (Role based access control) to Smart Contract to control ownership and right 

### ISSUE THREAD

**Issue by cloudvenger** [carbonable-labs/carbon-protocol-v3#42] opened 2024-04-30 09:31 UTC
**Description**
---
Adding Role Based Access Control (RBAC) to Project :
- [ ] Only role of Minter can `mint` and `batch_mint` tokenized CC.
- [ ] Only role of Owner can `set_project_carbon` and `set_absorption` in project
- [ ] Only role of Owner can `set_xxx` in the Minter
- [ ] Only role of Burner can `burn` and `batch_burn`  tokenized CC. 

**Additional context**
---
Using OpenZepplin Access Control Components to implement the RBAC in Carbon Protocol v3
[ Medium Difficulty  - Cairo- High Priority]

**Acceptance Criteria**
-----------------------
- [ ] Do relevant tests to ensure the correct behavior

**Comment by Khyati729** [comment] 2024-06-20 06:29
Contribute to Carbonable during ODHack:
Provable environmental infra

Go to the CarbonableOD Telegram: https://t.me/carbonableOD
Present yourself and tell us which issue you want to pick
Explain shortly how you want to tackle the issue
Ask a question if you need some clarity
When you're selected you will be assigned to the issue

**Comment by Khyati729** [comment] 2024-06-20 06:33
Contribute to Carbonable during ODHack: 
Provable environmental infra

- Go to the CarbonableOD Telegram: https://t.me/carbonableOD
- Present yourself and tell us which issue you want to pick
- Explain shortly how you want to tackle the issue
- Ask a question if you need some clarity
- When you're selected you will be assigned to the issue

**Comment by bitfalt** [comment] 2024-06-21 06:02
Hi! My name is Daniel and I recently stumbled upon OnlyDust, I'm a Computer Science student and I want to start contributing to open source projects. Also, I recently finished the Starklings tutorial and have done some quests in NodeGuardians.

The way I would tackle the issue is in the following way:
1. Read about OpenZepplin Access Control Components
2. Study the code to understand the different functions and how everything should be defined.
2. Start implementing each requirement one at a time
3. Once the implementation of said requirement is done, do the tests to ensure the correct behaviour.
4. Repeat steps 2 and 3 for each requirement.

Additionally, I would ask questions if a role isn't clear enough for me or if I needed clarification for something.

I love the whole idea of the project and would love to contribute to it. Thanks a lot for the opportunity!

**Closed as completed** 2024-06-27 15:39 UTC
Labels: good first issue, ODHack
